### Add Store Product to Cart
POST http://localhost:8080/cart/product
Content-Type: application/json

{
  "userId": "user101",
  "outletId": "store101",
  "productId": "product101"
}

### Get Cart (Pass relevant userId)
GET http://localhost:8080/cart/view?userId=user101
